### ISSUE TITLE
Initializing the W matrix to random entries is showing error on version 1.2.0

### ISSUE THREAD

**Issue by orpia** [GPflow/GPflow#847]
'A Simple Demonstration of Coregionalization' tutorial is showing error while executing the following lines in GPFlow version 1.2.0. I am using Tensorflow version 1.10.0 (No GPU)  and Python version 3.5.6 on Windows.

1. The following code works fine in version 1.0.0 but shows error in version 1.2.0
`m.kern.coregion.W = np.random.randn(2, 1)`

**AttributeError**: 'Sum' object has no attribute 'coregion'

2.  `m.kern.as_pandas_table()`

**AttributeError**: 'Prod' object has no attribute 'as_pandas_table'

Also, the following code snippets works in version 1.0.0 but not in version 1.2.0

3. 
```
output_dim = 3
lik = gpflow.likelihoods.SwitchedLikelihood([gpflow.likelihoods.StudentT()]*output_dim)
```
**ValueError** : self references are not allowed

4.  
```
m = gpflow.models.SVGP(X, Y, kern=kern, likelihood=lik, num_latent=1, Z=X[::3].copy()) 
m.compile()
m.kern.prod_1.coregion.W = np.random.randn(output_dim, R)
m.kern.prod_2.coregion.W = np.random.randn(output_dim, R)
```
**AttributeError**: 'Sum' object has no attribute 'prod_1'

**Comment by st--** [comment]
Hi, we've already fixed that bug but we're having some issues with getting readthedocs configured correctly... it's a bit confusing right now unfortunately. Sorry about that! Both the documentation in the "master" branch should work: https://gpflow.readthedocs.io/en/master/notebooks/coreg_demo.html and the actual notebook in the develop branch https://github.com/GPflow/GPflow/blob/develop/doc/source/notebooks/coreg_demo.ipynb should both work. (I've also fixed a bunch of typos that will be merged in with PR #849)
