### ISSUE TITLE
[ERROR] calling Parameter class

### ISSUE THREAD

**Issue by narnars0** [GPflow/GPflow#566]
I am using a current commit f42fc3e.

When I am calling Parameter class, below error is occurred. 

```
  File "/home/mlg/jtkim/workspace/GPflowBO/GPflowBO/bo.py", line 111, in optimize
    fun_ker = GPflow.kernels.RBF(X_train.shape[1], ARD=self.is_ard)
  File "/home/mlg/jtkim/venv/gpflowbo/lib/python3.4/site-packages/gpflow/core/compilable.py", line 86, in __init__
    origin_init(self, *args, **kwargs)
  File "/home/mlg/jtkim/venv/gpflowbo/lib/python3.4/site-packages/gpflow/core/compilable.py", line 86, in __init__
    origin_init(self, *args, **kwargs)
  File "/home/mlg/jtkim/venv/gpflowbo/lib/python3.4/site-packages/gpflow/kernels.py", line 360, in __init__
    self.variance = Parameter(variance, transform=transforms.positive)
  File "/home/mlg/jtkim/venv/gpflowbo/lib/python3.4/site-packages/gpflow/core/compilable.py", line 86, in __init__
    origin_init(self, *args, **kwargs)
  File "/home/mlg/jtkim/venv/gpflowbo/lib/python3.4/site-packages/gpflow/params/parameter.py", line 144, in __init__
    self._init_parameter_attributes(prior, transform, trainable)
  File "/home/mlg/jtkim/venv/gpflowbo/lib/python3.4/site-packages/gpflow/params/parameter.py", line 403, in _init_parameter_attributes
    self.transform = transform  # pylint: disable=W0201
  File "/home/mlg/jtkim/venv/gpflowbo/lib/python3.4/site-packages/gpflow/params/parameter.py", line 478, in __setattr__
    self._set_parameter_attribute(attr, value)
  File "/home/mlg/jtkim/venv/gpflowbo/lib/python3.4/site-packages/gpflow/params/parameter.py", line 428, in _set_parameter_attribute
    if value is not None and not isinstance(value, attr.interface):
  File "/home/mlg/jtkim/venv/gpflowbo/lib/python3.4/site-packages/gpflow/params/parameter.py", line 129, in interface
    if self.value == self.PRIOR.value:
AttributeError: 'ParameterAttribute' object has no attribute 'PRIOR'
```

Do you have any idea for this error?

**Comment by hughsalimbeni** [comment]
You're probably using python3.4. The enums are different. GPflow only works with 3.5

**Comment by narnars0** [comment]
It works! 
Thanks a lot.
