### ISSUE TITLE
Minor installation problems

### ISSUE THREAD

**Issue by icouckuy** [GPflow/GPflow#216]
I had to apply some fixes when installing GPflow master on opensuse tumbleweed with TF 0.11 and GCC 6:
- In setup.py also add " -D_GLIBCXX_USE_CXX11_ABI=0" for gcc version 6
otherwise I got an undefined symbol error
- In tf_wraps.py  change
@tf.python.framework.ops.RegisterGradient("VecToTri")
to
@tf.RegisterGradient("VecToTri")

It seems this is new in TF 0.11 (I'm not completely sure about this but otherwise I got a framework module not found error).

Now the tests start running but it seems many functions of TF have been moved/changed in 0.11, such as:
  File "/home/ilm/projecten/GPflow/GPflow/conditionals.py", line 91, in conditional
    L = tf.batch_matrix_band_part(tf.transpose(q_sqrt, (2, 0, 1)), -1, 0)  # D x M x M
AttributeError: 'module' object has no attribute 'batch_matrix_band_part'
or batch_cholesky

**Comment by ilm** [comment]
As a sidenote, what is currently the official supported TF version? And what is the policy regarding this, only support the latest versions or previous version too.  I assume the even older deep GP branch will be based on an older TF.

Btw: in the documentation it is still mentioned that GPflow is a pure python library and you just have to add it to your path. Of course this is no longer true with the user ops :)

**Comment by jameshensman** [comment]
Hi @icouckuy , thanks for the report!

Our general plan is to track the tensorflow releases, trying to stay up-to-date with what's going on over there. I just made a new branch tf11, where we can make changes that make the code work with the release. We'll not merge that into master until tf0.11 is officially released (so new users can install with pip). 

It looks form the release-notes that the 'batch_*' operations have been removed and the 'normal' operations now work as the batch ones did. 

https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/p1yk23KvH0c

We'll have to go through and make systematic changes I guess. Feel free to make PRs onto that branch if you want! Otherwise, everything should work with tf0.10, which is what we currently test against.

**Comment by icouckuy** [comment]
I did the required fixes in the branch + a PR. Everything seems to work (it was not that much).

The strange thing is I did not realize I was using a release candidate of TF. The getting started guide of TF already refers to 0.11, so users might get confused.

**Comment by jameshensman** [comment]
@icouckuy , did you add the code for gcc6 to setup.py also? I don't see it.

**Comment by icouckuy** [comment]
Not yet, it was not a specific tf11 fix. I was going to fix it in master.

**Comment by icouckuy** [comment]
Now this has been merged this can be closed
